name: CI
description: 'Running CI using docker and jfrog' 
on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs:
      using: docker
      image: Dockerfile
    steps:
      - name: Run Unit tests
        run: rpm test
